// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID        pgtype.UUID        `json:"id"`
	Fname     string             `json:"fname"`
	Lname     string             `json:"lname"`
	Email     string             `json:"email"`
	Age       int32              `json:"age"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Password  string             `json:"password"`
}
