// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.queries.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUserInDB = `-- name: CreateUserInDB :one
INSERT INTO users (fname, lname, email, age, password)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, fname, lname, email, age, created_at
`

type CreateUserInDBParams struct {
	Fname    string `json:"fname"`
	Lname    string `json:"lname"`
	Email    string `json:"email"`
	Age      int32  `json:"age"`
	Password string `json:"password"`
}

type CreateUserInDBRow struct {
	ID        pgtype.UUID        `json:"id"`
	Fname     string             `json:"fname"`
	Lname     string             `json:"lname"`
	Email     string             `json:"email"`
	Age       int32              `json:"age"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateUserInDB(ctx context.Context, arg CreateUserInDBParams) (CreateUserInDBRow, error) {
	row := q.db.QueryRow(ctx, createUserInDB,
		arg.Fname,
		arg.Lname,
		arg.Email,
		arg.Age,
		arg.Password,
	)
	var i CreateUserInDBRow
	err := row.Scan(
		&i.ID,
		&i.Fname,
		&i.Lname,
		&i.Email,
		&i.Age,
		&i.CreatedAt,
	)
	return i, err
}
